name: CursedCombat
version: 1.0.0
main: com.cstudioss.cursedcombat.CursedCombatPlugin
api-version: '1.20'
commands:
  curse:
    description: Base command for Cursed Combat.
    usage: /curse <stats|cast|settechnique|reload>
    permission: cursedcombat.use
permissions:
  cursedcombat.use:
    description: Allows using basic curse commands.
    default: true
  cursedcombat.cast:
    description: Allows casting abilities via command.
    default: op
  cursedcombat.admin:
    description: Allows admin curse commands.
    default: op
